# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapchatClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapchatClone
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'FirebaseCore'

  target 'SnapchatCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapchatCloneUITests' do
    # Pods for testing
  end

end
